sensor_msgs/Image image
bool arr_present1
uint16 x1
uint16 y1
uint16 w1
uint16 h1
bool arr_present2
uint16 x2
uint16 y2
uint16 w2
uint16 h2
bool cone_present1
uint16 x3
uint16 y3
uint16 w3
uint16 h3
bool cone_present2
uint16 x4
uint16 y4
uint16 w4
uint16 h4
---
bool isArrowFound
bool isArrowRight
bool isConeFound
float64 arrow_x
float64 arrow_y
float64 cone_x
float64 cone_y
